
services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5433:${TEST_DB_PORT}"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  backend_test:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      PYTHONPATH: /app
    env_file: .env
    depends_on:
      - test_db
    command: ["poetry", "run", "pytest", "--disable-warnings"]

volumes:
  test_db_data: