
services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  backend_test:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: ${TEST_DATABASE_URL}
      PYTHONPATH: /app
    depends_on:
      - test_db
    command: ["poetry", "run", "pytest", "--disable-warnings"]

volumes:
  test_db_data: