import pytest
from app.concentrate.schemas import SConcentrateCreate, SConcentrateUpdate
from app.concentrate.services.create_concentrate import create_concentrate_service
from app.concentrate.services.get_all_concentrates import get_all_concentrates_service
from app.concentrate.services.get_concentrate_by_id import get_concentrate_by_id_service
from app.concentrate.services.update_concentrate import update_concentrate_service
from app.concentrate.services.delete_concentrate import delete_concentrate_service
from app.concentrate.services.get_concentrate_statistics import get_concentrate_statistics_service
from app.users.schemas import SUserCreate
from app.users.services.create_user import create_user_service
from app.concentrate.exceptions import ConcentrateNotFound
from app.users.models import User



